version: '3.8'

services:
  bots312:
    build:
      context: .
      dockerfile: ./docker/bots_py312/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - DB_ENGINE=postgresql
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bots
      POSTGRES_PASSWORD: botsbots
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/bots_py312/postgres_db:/docker-entrypoint-initdb.d
    restart: unless-stopped
volumes:
  postgres_data:

